import 'server-only'

import ExcelJS from 'exceljs'
import { DEAL_EXPORT_COLUMNS, type DealExportColumn, type DealExportRow, STATUS_COLORS } from './deal-export-columns'
import { getStageColor, DEAL_PIPELINE_STAGES } from '@/lib/deal-pipeline'

const HEADER_FILL: ExcelJS.Fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FF0F1D3A' } }
const HEADER_FONT: Partial<ExcelJS.Font> = { color: { argb: 'FFFFFFFF' }, bold: true, size: 10, name: 'Calibri' }
const TITLE_FONT: Partial<ExcelJS.Font> = { bold: true, size: 18, color: { argb: 'FF0F1D3A' }, name: 'Calibri' }
const VALUE_FONT: Partial<ExcelJS.Font> = { size: 10, color: { argb: 'FF1E293B' }, name: 'Calibri' }
const SUBTITLE_FONT: Partial<ExcelJS.Font> = { size: 9, color: { argb: 'FF64748B' }, name: 'Calibri' }

const BORDER_COLOR = 'FFCBD5E1'
const THIN_BORDER: Partial<ExcelJS.Borders> = {
  top: { style: 'thin', color: { argb: BORDER_COLOR } },
  bottom: { style: 'thin', color: { argb: BORDER_COLOR } },
  left: { style: 'thin', color: { argb: BORDER_COLOR } },
  right: { style: 'thin', color: { argb: BORDER_COLOR } },
}

const GROUP_FILLS = [
  { argb: 'FFEFF6FF' },
  { argb: 'FFF0FDF4' },
  { argb: 'FFFFFBEB' },
  { argb: 'FFF5F3FF' },
  { argb: 'FFFEF2F2' },
  { argb: 'FFECFEFF' },
  { argb: 'FFFFF7ED' },
]

const STATUS_FILLS: Record<string, ExcelJS.Fill> = {}
for (const stage of DEAL_PIPELINE_STAGES) {
  const color = getStageColor(stage.id)
  const [r, g, b] = [color.slice(1, 3), color.slice(3, 5), color.slice(5, 7)]
  STATUS_FILLS[stage.label] = { type: 'pattern', pattern: 'solid', fgColor: { argb: `FF${r}${g}${b}20` } }
}

const GROUPS = Array.from(new Set(DEAL_EXPORT_COLUMNS.map((c) => c.group)))

function colLetter(n: number): string {
  let s = ''
  let v = n
  while (v > 0) {
    const r = (v - 1) % 26
    s = String.fromCharCode(65 + r) + s
    v = Math.floor((v - 1) / 26)
  }
  return s
}

function exportDate(date: Date): string {
  return date.toLocaleDateString('en-GB', { day: '2-digit', month: 'short', year: 'numeric' })
}

function formatCellValue(raw: unknown, col: DealExportColumn): ExcelJS.CellValue {
  if (raw === null || raw === undefined || raw === '' || raw === '—') return ''
  const str = String(raw)
  if (str === '—') return ''

  if (col.type === 'date') {
    // Try to parse ISO dates into real Excel dates.
    if (/^\d{4}-\d{2}-\d{2}/.test(str)) {
      const d = new Date(str)
      if (!Number.isNaN(d.getTime())) {
        return d
      }
    }
    // Free text date like "Next Month" — keep as string.
    return str
  }

  if (col.type === 'link' && str) {
    return { text: str, hyperlink: `mailto:${str}` }
  }

  return str
}

function writeSummarySheet(wb: ExcelJS.Workbook, rows: DealExportRow[], meta: { organizationName: string; generatedBy: string; generatedAt: Date; filters: string[]; truncated?: { shown: number; total: number } }): void {
  const ws = wb.addWorksheet('Summary', {
    properties: { tabColor: { argb: 'FF0F1D3A' } },
    views: [{ showGridLines: false }],
  })

  let row = 1
  ws.getCell(`A${row}`).value = 'Deals Export'
  ws.getCell(`A${row}`).font = TITLE_FONT
  ws.getCell(`A${row}`).alignment = { vertical: 'middle' }
  ws.getRow(row).height = 32
  row += 1

  ws.getCell(`A${row}`).value = meta.organizationName || 'Organization'
  ws.getCell(`A${row}`).font = { size: 12, bold: true, color: { argb: 'FF1E293B' }, name: 'Calibri' }
  ws.getRow(row).height = 22
  row += 2

  const filterApplied = meta.filters.length > 0 ? meta.filters.join('; ') : 'No filters applied'
  const metaPairs: [string, string][] = [
    ['Generated on', exportDate(meta.generatedAt)],
    ['Generated by', meta.generatedBy || '—'],
    ['Total deals exported', String(rows.length)],
    ['Filters applied', filterApplied],
  ]

  let col = 1
  for (const [label, value] of metaPairs) {
    ws.getCell(row, col).value = label
    ws.getCell(row, col).font = { size: 10, bold: true, color: { argb: 'FF334155' }, name: 'Calibri' }
    ws.getCell(row, col + 1).value = value
    ws.getCell(row, col + 1).font = { size: 10, color: { argb: 'FF1E293B' }, name: 'Calibri' }
    row += 1
  }

  if (meta.truncated) {
    row += 1
    ws.getCell(`A${row}`).value = `⚠ Showing ${meta.truncated.shown} of ${meta.truncated.total} deals`
    ws.getCell(`A${row}`).font = { size: 10, bold: true, color: { argb: 'FFB45309' }, name: 'Calibri' }
    ws.getCell(`A${row}`).fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FFFFFBEB' } }
    row += 1
  }

  row += 1

  const breakdowns: { title: string; key: string }[] = [
    { title: 'Deals by Status', key: 'status' },
    { title: 'Deals by Grade', key: 'grade' },
    { title: 'Deals by Country', key: 'country' },
    { title: 'Deals by Lead source', key: 'leadSource' },
  ]

  for (const bd of breakdowns) {
    const counts = new Map<string, number>()
    for (const r of rows) {
      const val = (bd.key === 'leadSource' ? r.leadSource : (r as any)[bd.key]) || 'Not specified'
      counts.set(val, (counts.get(val) || 0) + 1)
    }
    const sorted = Array.from(counts.entries()).sort((a, b) => b[1] - a[1])

    ws.getCell(`A${row}`).value = bd.title
    ws.getCell(`A${row}`).font = { size: 11, bold: true, color: { argb: 'FF0F1D3A' }, name: 'Calibri' }
    ws.getCell(`A${row}`).border = { bottom: { style: 'thin', color: { argb: 'FF0F1D3A' } } }
    row += 1

    const hRow = ws.getRow(row)
    hRow.getCell(1).value = 'Value'
    hRow.getCell(2).value = 'Count'
    hRow.getCell(1).font = { bold: true, size: 9, color: { argb: 'FFFFFFFF' }, name: 'Calibri' }
    hRow.getCell(2).font = { bold: true, size: 9, color: { argb: 'FFFFFFFF' }, name: 'Calibri' }
    hRow.getCell(1).fill = HEADER_FILL
    hRow.getCell(2).fill = HEADER_FILL
    hRow.getCell(1).border = THIN_BORDER
    hRow.getCell(2).border = THIN_BORDER
    hRow.height = 18
    row += 1

    for (const [val, cnt] of sorted) {
      ws.getCell(`A${row}`).value = val
      ws.getCell(`B${row}`).value = cnt
      ws.getCell(`A${row}`).font = { size: 9, name: 'Calibri' }
      ws.getCell(`B${row}`).font = { size: 9, name: 'Calibri' }
      ws.getCell(`A${row}`).border = THIN_BORDER
      ws.getCell(`B${row}`).border = THIN_BORDER
      if (row % 2 === 0) {
        ws.getCell(`A${row}`).fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FFF8FAFC' } }
        ws.getCell(`B${row}`).fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FFF8FAFC' } }
      }
      row += 1
    }
    row += 1
  }

  ws.getColumn(1).width = 24
  ws.getColumn(2).width = 10
}

function writeDealsSheet(wb: ExcelJS.Workbook, rows: DealExportRow[]): void {
  const ws = wb.addWorksheet('Deals', {
    properties: { tabColor: { argb: 'FF0F1D3A' } },
  })

  const colCount = DEAL_EXPORT_COLUMNS.length

  // Row 1: Group band
  const groupRow = ws.getRow(1)
  const groupStart = new Map<string, number>()
  const groupEnd = new Map<string, number>()

  DEAL_EXPORT_COLUMNS.forEach((col, i) => {
    const start = groupStart.get(col.group) ?? i + 1
    groupStart.set(col.group, start)
    groupEnd.set(col.group, i + 1)
  })

  let gIdx = 0
  for (const group of GROUPS) {
    const start = groupStart.get(group)!
    const end = groupEnd.get(group)!
    if (start < end) {
      ws.mergeCells(1, start, 1, end)
      const cell = groupRow.getCell(start)
      cell.value = group
      cell.font = { bold: true, size: 10, color: { argb: 'FFFFFFFF' }, name: 'Calibri' }
      cell.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: GROUP_FILLS[gIdx % GROUP_FILLS.length].argb } }
      cell.alignment = { horizontal: 'center', vertical: 'middle' }
      cell.border = THIN_BORDER
    }
    gIdx++
  }
  groupRow.height = 22

  // Row 2: Headers
  const headerRow = ws.getRow(2)
  DEAL_EXPORT_COLUMNS.forEach((col, i) => {
    const cell = headerRow.getCell(i + 1)
    cell.value = col.header
    cell.fill = HEADER_FILL
    cell.font = HEADER_FONT
    cell.alignment = { horizontal: 'center', vertical: 'middle', wrapText: true }
    cell.border = THIN_BORDER
  })
  headerRow.height = 30

  // Data rows
  const dataStartRow = 3
  const wrapCols = new Set(DEAL_EXPORT_COLUMNS.filter((c) => c.wrap).map((c) => c.key))

  for (let i = 0; i < rows.length; i++) {
    const r = rows[i]
    const excelRow = ws.getRow(dataStartRow + i)
    const isEven = i % 2 === 0

    DEAL_EXPORT_COLUMNS.forEach((col, j) => {
      const cell = excelRow.getCell(j + 1)
      const raw = col.accessor(r)
      const value = formatCellValue(raw, col)

      cell.value = value
      cell.font = VALUE_FONT
      cell.border = THIN_BORDER
      cell.alignment = {
        horizontal: col.type === 'number' ? 'right' : 'left',
        vertical: 'top',
        wrapText: wrapCols.has(col.key),
      }

      if (col.key === 'pincode' || col.key === 'contactNumber') {
        cell.numFmt = '@'
      }
      if (col.type === 'date' && value instanceof Date) {
        cell.numFmt = 'dd-mmm-yyyy'
      }

      if (isEven) {
        cell.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FFF8FAFC' } }
      }

      if (col.key === 'status') {
        const fill = STATUS_FILLS[String(raw)]
        if (fill) cell.fill = fill
      }

      if (col.key === 'email' && typeof raw === 'string' && raw) {
        cell.value = { text: raw, hyperlink: `mailto:${raw}` }
      }
    })

    excelRow.height = 18
  }

  const dataEndRow = dataStartRow + rows.length - 1

  // Column widths
  DEAL_EXPORT_COLUMNS.forEach((col, i) => {
    ws.getColumn(i + 1).width = col.width
  })

  // Freeze panes: rows 1-2 and first 3 columns
  if (rows.length > 0) {
    ws.views = [{ state: 'frozen', xSplit: 3, ySplit: 2 }]
    ws.autoFilter = {
      from: { row: 2, column: 1 },
      to: { row: 2, column: colCount },
    }
  }

  // Print setup
  ws.pageSetup = {
    paperSize: 9,
    orientation: 'landscape',
    fitToPage: true,
    fitToWidth: 1,
    fitToHeight: 0,
    margins: { left: 0.3, right: 0.3, top: 0.5, bottom: 0.5, header: 0.2, footer: 0.2 },
    printTitlesRow: '1:2',
  }
  ws.headerFooter.oddHeader = '&C&16&K0F1D3A Deals Export'
  ws.headerFooter.oddFooter = '&L&8&K808080 Kawman ExAct  •  Deals   &C&8&K808080 &D   &R&8&K808080 Page &P of &N'
}

function writeNotesSheet(wb: ExcelJS.Workbook): void {
  const ws = wb.addWorksheet('Notes', {
    properties: { tabColor: { argb: 'FF7C3AED' } },
    views: [{ showGridLines: false }],
  })

  let row = 1
  ws.getCell(`A${row}`).value = 'Column Guide'
  ws.getCell(`A${row}`).font = TITLE_FONT
  ws.getRow(row).height = 28
  row += 1

  const hRow = ws.getRow(row)
  hRow.getCell(1).value = 'Column'
  hRow.getCell(2).value = 'Group'
  hRow.getCell(3).value = 'Description'
  hRow.getCell(1).font = HEADER_FONT
  hRow.getCell(2).font = HEADER_FONT
  hRow.getCell(3).font = HEADER_FONT
  hRow.getCell(1).fill = HEADER_FILL
  hRow.getCell(2).fill = HEADER_FILL
  hRow.getCell(3).fill = HEADER_FILL
  hRow.getCell(1).border = THIN_BORDER
  hRow.getCell(2).border = THIN_BORDER
  hRow.getCell(3).border = THIN_BORDER
  hRow.height = 20
  row += 1

  const descriptions: Record<string, string> = {
    No: 'Running serial number (1..n), not the DB id.',
    Date: 'Meeting or lead date, formatted as DD-MMM-YYYY. Free text preserved if not a real date.',
    'Customer Name': 'Company name associated with the deal.',
    City: 'City of the customer.',
    Country: 'Country of the customer.',
    Pincode: 'Postal / pin code, exported as text to preserve leading zeros.',
    'Contact Person': 'Primary contact name for the deal.',
    'Contact Number': 'Phone number, exported as text to preserve formatting and leading zeros.',
    Designation: 'Job title of the contact person.',
    Email: 'Email address with mailto hyperlink in Excel.',
    'Lead source': 'How the lead was acquired.',
    'Purpose of Visit': 'Reason for the meeting or enquiry.',
    'Meeting at': 'Meeting location or mode (e.g. Virtual, Office).',
    'Products Discussed': 'Products selected in the deal, joined by comma.',
    'Key Discussion Points': 'Summary of key talking points.',
    'Customer Requirement': 'Stated requirement from the customer.',
    Grade: 'Customer or deal grade (e.g. Nutraceutical, Cosmetic).',
    Status: 'Current pipeline stage (e.g. Suspect, Prospect, Negotiate, Closed).',
    'CDA Status / date': 'CDA status text.',
    'Sampling Status': 'Sampling status text.',
    'Feedback From R&D Team': 'R&D feedback text.',
    Remark: 'Internal remarks or follow-up notes.',
    'Next Follow-up': 'Next follow-up date, formatted as DD-MMM-YYYY. Free text preserved.',
    LOA: 'LOA status text.',
  }

  for (const col of DEAL_EXPORT_COLUMNS) {
    const desc = descriptions[col.header] || ''
    ws.getCell(`A${row}`).value = col.header
    ws.getCell(`B${row}`).value = col.group
    ws.getCell(`C${row}`).value = desc
    ws.getCell(`A${row}`).font = { size: 9, name: 'Calibri' }
    ws.getCell(`B${row}`).font = { size: 9, name: 'Calibri', color: { argb: 'FF64748B' } }
    ws.getCell(`C${row}`).font = { size: 9, name: 'Calibri' }
    ws.getCell(`A${row}`).border = THIN_BORDER
    ws.getCell(`B${row}`).border = THIN_BORDER
    ws.getCell(`C${row}`).border = THIN_BORDER
    ws.getCell(`C${row}`).alignment = { wrapText: true }
    if (row % 2 === 0) {
      ws.getCell(`A${row}`).fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FFF8FAFC' } }
      ws.getCell(`B${row}`).fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FFF8FAFC' } }
      ws.getCell(`C${row}`).fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FFF8FAFC' } }
    }
    ws.getRow(row).height = 18
    row += 1
  }

  row += 1
  ws.getCell(`A${row}`).value = 'Status Color Legend'
  ws.getCell(`A${row}`).font = { bold: true, size: 11, color: { argb: 'FF0F1D3A' }, name: 'Calibri' }
  ws.getRow(row).height = 22
  row += 1

  const legendRow = ws.getRow(row)
  legendRow.getCell(1).value = 'Status'
  legendRow.getCell(2).value = 'Color meaning'
  legendRow.getCell(1).font = HEADER_FONT
  legendRow.getCell(2).font = HEADER_FONT
  legendRow.getCell(1).fill = HEADER_FILL
  legendRow.getCell(2).fill = HEADER_FILL
  legendRow.getCell(1).border = THIN_BORDER
  legendRow.getCell(2).border = THIN_BORDER
  legendRow.height = 18
  row += 1

  const legendEntries: [string, string][] = DEAL_PIPELINE_STAGES.map((s) => [
    s.label,
    s.description,
  ])

  for (const [status, meaning] of legendEntries) {
    const fill = STATUS_FILLS[status]
    ws.getCell(`A${row}`).value = status
    ws.getCell(`B${row}`).value = meaning
    ws.getCell(`A${row}`).font = { size: 9, name: 'Calibri' }
    ws.getCell(`B${row}`).font = { size: 9, name: 'Calibri' }
    ws.getCell(`A${row}`).border = THIN_BORDER
    ws.getCell(`B${row}`).border = THIN_BORDER
    if (fill) ws.getCell(`A${row}`).fill = fill
    if (row % 2 === 0) {
      ws.getCell(`B${row}`).fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FFF8FAFC' } }
    }
    row += 1
  }

  ws.getColumn(1).width = 22
  ws.getColumn(2).width = 50
  ws.getColumn(3).width = 60
}

export async function buildDealExportWorkbook(rows: DealExportRow[], meta: { organizationName: string; generatedBy: string; generatedAt: Date; filters: string[]; truncated?: { shown: number; total: number } }): Promise<Buffer> {
  const wb = new ExcelJS.Workbook()
  wb.creator = meta.organizationName || 'Kawman ExAct'
  wb.created = meta.generatedAt
  wb.properties.date1904 = false

  writeSummarySheet(wb, rows, meta)
  writeDealsSheet(wb, rows)
  writeNotesSheet(wb)

  const buffer = await wb.xlsx.writeBuffer()
  return Buffer.from(buffer)
}
