/**
 * Generic Excel workbook builder using exceljs.
 * Reusable across all CRM entity exports (companies, contacts, deals, audit-logs, etc.).
 */
import ExcelJS from 'exceljs'

export interface ExportMeta {
  organizationName: string
  generatedBy: string
  generatedAt: Date
  filterLines: string[]
  truncated?: { shown: number; total: number }
}

export interface ExportColumn<T> {
  header: string
  key: string
  width: number
  format?: string
  align?: 'left' | 'right'
  render?: (row: T) => string | number | Date | null | undefined
}

export interface SheetDefinition<T> {
  name: string
  title: string
  columns: ExportColumn<T>[]
  rows: T[]
  totals?: { key: string; label: string; colLetter: string; format?: string }[]
}

const HEADER_FILL: ExcelJS.Fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FF0F1D3A' } }
const HEADER_FONT: Partial<ExcelJS.Font> = { color: { argb: 'FFFFFFFF' }, bold: true, size: 10, name: 'Calibri' }
const TITLE_FONT: Partial<ExcelJS.Font> = { bold: true, size: 18, color: { argb: 'FF0F1D3A' }, name: 'Calibri' }
const LABEL_FONT: Partial<ExcelJS.Font> = { bold: true, size: 10, color: { argb: 'FF334155' }, name: 'Calibri' }
const VALUE_FONT: Partial<ExcelJS.Font> = { size: 10, color: { argb: 'FF1E293B' }, name: 'Calibri' }
const SUBTITLE_FONT: Partial<ExcelJS.Font> = { size: 9, color: { argb: 'FF64748B' }, name: 'Calibri' }

const BORDER_COLOR = 'FFCBD5E1'
const THIN_BORDER: Partial<ExcelJS.Borders> = {
  top: { style: 'thin', color: { argb: BORDER_COLOR } },
  left: { style: 'thin', color: { argb: BORDER_COLOR } },
  bottom: { style: 'thin', color: { argb: BORDER_COLOR } },
  right: { style: 'thin', color: { argb: BORDER_COLOR } },
}

function colLetter(n: number): string {
  let s = ''
  let v = n
  while (v > 0) {
    const r = (v - 1) % 26
    s = String.fromCharCode(65 + r) + s
    v = Math.floor((v - 1) / 26)
  }
  return s
}

function exportDate(date: Date): string {
  return date.toLocaleDateString('en-GB', { day: '2-digit', month: 'short', year: 'numeric' })
}

function addMetaBlock(ws: ExcelJS.Worksheet, meta: ExportMeta, colCount: number): number {
  let row = 1

  ws.getCell(`A${row}`).value = meta.filterLines.length > 0 ? meta.filterLines[0].split(':')[0] : 'Report'
  ws.getCell(`A${row}`).font = TITLE_FONT
  ws.getCell(`A${row}`).alignment = { vertical: 'middle' }
  ws.mergeCells(`A${row}:${colLetter(colCount)}${row}`)
  ws.getRow(row).height = 32
  row += 1

  ws.getCell(`A${row}`).value = meta.organizationName
  ws.getCell(`A${row}`).font = { size: 12, bold: true, color: { argb: 'FF1E293B' }, name: 'Calibri' }
  ws.mergeCells(`A${row}:${colLetter(colCount)}${row}`)
  ws.getRow(row).height = 22
  row += 1

  const metaLine = `Report date: ${exportDate(meta.generatedAt)}    |    Generated by: ${meta.generatedBy}`
  ws.getCell(`A${row}`).value = metaLine
  ws.getCell(`A${row}`).font = { size: 9, color: { argb: 'FF64748B' }, name: 'Calibri' }
  ws.mergeCells(`A${row}:${colLetter(colCount)}${row}`)
  row += 1

  if (meta.filterLines.length > 0) {
    row += 1
    ws.getCell(`A${row}`).value = 'APPLIED FILTERS'
    ws.getCell(`A${row}`).font = { size: 9, bold: true, color: { argb: 'FF0F1D3A' }, name: 'Calibri' }
    ws.getCell(`A${row}`).border = { bottom: { style: 'thin', color: { argb: 'FF0F1D3A' } } }
    ws.getRow(row).height = 18
    row += 1
    for (const line of meta.filterLines) {
      ws.getCell(`A${row}`).value = `• ${line}`
      ws.getCell(`A${row}`).font = { size: 9, color: { argb: 'FF475569' }, name: 'Calibri' }
      ws.getRow(row).height = 16
      row += 1
    }
  }

  if (meta.truncated) {
    row += 1
    ws.mergeCells(`A${row}:${colLetter(colCount)}${row}`)
    ws.getCell(`A${row}`).value = `⚠ TRUNCATED: showing the first ${meta.truncated.shown} of ${meta.truncated.total} matching rows.`
    ws.getCell(`A${row}`).font = { size: 9, bold: true, color: { argb: 'FFB45309' }, name: 'Calibri' }
    ws.getCell(`A${row}`).fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FFFFFBEB' } }
    ws.getCell(`A${row}`).border = { top: { style: 'thin', color: { argb: 'FFE2E8F0' } }, bottom: { style: 'thin', color: { argb: 'FFE2E8F0' } } }
    ws.getRow(row).height = 18
    row += 1
  }

  row += 1
  return row
}

function styleHeaderRow(ws: ExcelJS.Worksheet, headerRowNumber: number, colCount: number) {
  const headerRow = ws.getRow(headerRowNumber)
  for (let i = 1; i <= colCount; i++) {
    const cell = headerRow.getCell(i)
    cell.fill = HEADER_FILL
    cell.font = HEADER_FONT
    cell.alignment = { vertical: 'middle', horizontal: 'center', wrapText: true }
    cell.border = THIN_BORDER
  }
  headerRow.height = 26
}

function writeDataRows<T>(
  ws: ExcelJS.Worksheet,
  dataStartRow: number,
  columns: ExportColumn<T>[],
  rows: T[]
): number {
  let dataRowNumber = dataStartRow - 1
  const evenFill: ExcelJS.Fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FFFAFAFA' } }
  const oddFill: ExcelJS.Fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FFFFFFFF' } }

  for (const record of rows) {
    dataRowNumber++
    const excelRow = ws.getRow(dataRowNumber)
    const isEven = (dataRowNumber - dataStartRow) % 2 === 0

    for (let i = 0; i < columns.length; i++) {
      const col = columns[i]
      const cell = excelRow.getCell(i + 1)
      let value = col.render ? col.render(record) : (record as Record<string, unknown>)[col.key]

      if (Array.isArray(value)) {
        value = value.length > 0 ? value.join(', ') : '—'
      } else if (value === null || value === undefined || value === '') {
        value = '—'
      }

      cell.value = value as ExcelJS.CellValue
      cell.font = VALUE_FONT
      cell.border = THIN_BORDER
      cell.alignment = { horizontal: col.align ?? 'left', vertical: 'middle', wrapText: true }
      if (col.format) cell.numFmt = col.format
      if (value instanceof Date) {
        cell.numFmt = 'dd-mmm-yyyy'
        cell.value = value
      }
      cell.fill = isEven ? evenFill : oddFill
    }
    excelRow.height = 20
  }
  return dataRowNumber
}

function addTotalsRow(
  ws: ExcelJS.Worksheet,
  dataStartRow: number,
  dataRowNumber: number,
  columns: ExportColumn<unknown>[],
  totals: { key: string; label: string; colLetter: string; format?: string }[]
) {
  const totalsRow = ws.getRow(dataRowNumber + 1)
  totalsRow.getCell(1).value = totals[0]?.label ?? 'TOTAL'
  totalsRow.getCell(1).font = { bold: true, size: 10, color: { argb: 'FF0F1D3A' }, name: 'Calibri' }
  totalsRow.getCell(1).border = { top: { style: 'medium', color: { argb: 'FF0F1D3A' } }, bottom: { style: 'medium', color: { argb: 'FF0F1D3A' } } }
  totalsRow.getCell(1).fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FFEFF6FF' } }

  for (const { key, colLetter, format } of totals) {
    const colIndex = columns.findIndex((c) => c.key === key) + 1
    if (colIndex > 0) {
      const cell = totalsRow.getCell(colIndex)
      cell.value = { formula: `SUM(${colLetter}${dataStartRow}:${colLetter}${dataRowNumber})` }
      cell.font = { bold: true, size: 10, color: { argb: 'FF0F1D3A' }, name: 'Calibri' }
      cell.numFmt = format ?? '#,##0.00'
      cell.alignment = { horizontal: 'right', vertical: 'middle' }
      cell.border = { top: { style: 'medium', color: { argb: 'FF0F1D3A' } }, bottom: { style: 'medium', color: { argb: 'FF0F1D3A' } } }
      cell.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FFEFF6FF' } }
    }
  }
  totalsRow.height = 22
}

function setupSheetFinalization(
  ws: ExcelJS.Worksheet,
  headerRowNumber: number,
  dataStartRow: number,
  dataRowNumber: number,
  colCount: number,
  meta: ExportMeta
) {
  if (dataRowNumber >= dataStartRow) {
    ws.autoFilter = {
      from: { row: headerRowNumber, column: 1 },
      to: { row: dataRowNumber, column: colCount },
    }
    ws.views = [{ state: 'frozen', xSplit: 0, ySplit: headerRowNumber }]
    ws.pageSetup = {
      paperSize: 9,
      orientation: 'landscape',
      fitToPage: true,
      fitToWidth: 1,
      fitToHeight: 0,
      margins: { left: 0.3, right: 0.3, top: 0.5, bottom: 0.5, header: 0.2, footer: 0.2 },
      printTitlesRow: `${headerRowNumber}:${headerRowNumber}`,
    }
    ws.headerFooter.oddFooter = `&L&8&K808080 ${meta.organizationName}  •  ${meta.filterLines[0]?.split(':')[0] ?? 'Report'}   &C&8&K808080 ${exportDate(meta.generatedAt)}   &R&8&K808080 Page &P of &N`
  }
}

export async function buildWorkbook<T>(input: {
  sheets: SheetDefinition<T>[]
  meta: ExportMeta
}): Promise<Buffer> {
  const wb = new ExcelJS.Workbook()
  wb.creator = input.meta.organizationName || 'Kawman ExAct'
  wb.created = input.meta.generatedAt

  for (const sheetDef of input.sheets) {
    const ws = wb.addWorksheet(sheetDef.name, {
      properties: { tabColor: { argb: 'FF0F1D3A' } },
    })

    const colCount = sheetDef.columns.length

    const headerRowNumber = addMetaBlock(ws, input.meta, colCount)
    styleHeaderRow(ws, headerRowNumber, colCount)

    const dataStartRow = headerRowNumber + 1
    const dataRowNumber = writeDataRows(ws, dataStartRow, sheetDef.columns, sheetDef.rows)

    if (sheetDef.totals && dataRowNumber >= dataStartRow) {
      addTotalsRow(ws, dataStartRow, dataRowNumber, sheetDef.columns as ExportColumn<unknown>[], sheetDef.totals)
    }

    setupSheetFinalization(ws, headerRowNumber, dataStartRow, dataRowNumber, colCount, input.meta)

    sheetDef.columns.forEach((col, i) => {
      ws.getColumn(i + 1).width = Math.max(12, Math.min(48, col.width))
    })

    ws.getColumn(colCount + 1).width = 2
  }

  const buffer = await wb.xlsx.writeBuffer()
  return Buffer.from(buffer)
}
