import { formatCurrency } from '@/lib/utils'
import { PAYMENT_STATUS_LABEL } from '@/lib/sales-schema'
import type { PaymentStatus } from '@/lib/sales-money'
import { describeSalesFilters } from '@/lib/sales-filters'
import type { SalesPageData } from '@/types/sales'

const STATUS_INK: Record<PaymentStatus, string> = {
  PAID: '#166534',
  PARTIALLY_PAID: '#92400e',
  PENDING: '#9f1239',
}

function qty(value: number | null, byUnit: Array<{ unit: string; quantity: number }>, fallbackUnit: string): string {
  if (byUnit.length === 0) return `${value ?? 0} ${fallbackUnit}`.trim()
  if (byUnit.length === 1) return `${byUnit[0].quantity} ${byUnit[0].unit}`
  return byUnit.map((q) => `${q.quantity} ${q.unit}`).join(' / ')
}

/**
 * Light-background, no-chrome rendering used for /sales-tracking?print=1.
 *
 * It reuses the SAME server-fetched page data as the interactive page, so the
 * printed numbers are the numbers on screen. No MainLayout, no dark theme — dark
 * backgrounds waste toner and most browsers drop background colours when
 * printing anyway.
 */
export function SalesPrintView({
  data,
  organizationName,
  generatedBy,
}: {
  data: SalesPageData
  organizationName: string
  generatedBy: string
}) {
  const filterLines = describeSalesFilters(data.filters, data.filterLabels)

  return (
    <div className="min-h-screen bg-white p-6 text-slate-900">
      <header className="border-b-2 border-slate-900 pb-3">
        <div className="flex items-start justify-between gap-6">
          <div>
            <h1 className="text-xl font-bold tracking-tight">Sales Product Tracking Report</h1>
            <p className="mt-0.5 text-sm text-slate-600">{organizationName}</p>
          </div>
          <div className="text-right text-xs text-slate-600">
            <p>Report date: {new Date().toLocaleDateString('en-GB')}</p>
            <p>Generated by: {generatedBy}</p>
            <p>
              {data.rows.length} of {data.total} matching rows
            </p>
          </div>
        </div>
      </header>

      <section className="mt-3 text-xs text-slate-700">
        <strong className="font-semibold">Applied filters:</strong>{' '}
        {filterLines.length > 0 ? filterLines.join('  |  ') : 'None (all records)'}
      </section>

      <section className="mt-4 grid grid-cols-5 gap-3">
        <Summary label="Total Sales" value={String(data.kpis.totalSales)} />
        <Summary
          label="Total Quantity"
          value={qty(data.kpis.totalQuantity, data.kpis.quantityByUnit, '')}
        />
        <Summary label="Sales Value" value={formatCurrency(data.kpis.totalSalesValue)} />
        <Summary label="Paid" value={formatCurrency(data.kpis.totalAmountPaid)} />
        <Summary label="Pending" value={formatCurrency(data.kpis.totalPendingAmount)} />
      </section>

      {data.truncated && (
        <p className="mt-3 border-l-4 border-amber-500 bg-amber-50 px-3 py-1.5 text-xs text-amber-900">
          Totals cover only the first 50,000 matching lines. Narrow the filters for an exact figure.
        </p>
      )}

      <table className="mt-4 w-full border-collapse text-[11px]">
        <thead>
          <tr className="border-y border-slate-400 bg-slate-100 text-left">
            {['Date', 'Salesperson', 'Customer', 'Product', 'Invoice', 'Qty', 'Unit', 'Unit Price', 'Total', 'Paid', 'Balance', 'Status'].map(
              (head, index) => (
                <th
                  key={head}
                  className={`px-1.5 py-1.5 font-semibold ${index >= 5 && index <= 6 ? '' : index >= 7 && index <= 10 ? 'text-right' : ''}`}
                >
                  {head}
                </th>
              )
            )}
          </tr>
        </thead>
        <tbody>
          {data.rows.map((row) => (
            <tr key={row.id} className="border-b border-slate-200">
              <td className="px-1.5 py-1 whitespace-nowrap">{row.saleDate.slice(0, 10)}</td>
              <td className="px-1.5 py-1">{row.salespersonName}</td>
              <td className="px-1.5 py-1">{row.customerName}</td>
              <td className="px-1.5 py-1">{row.productName}</td>
              <td className="px-1.5 py-1 whitespace-nowrap">{row.invoiceNumber}</td>
              <td className="px-1.5 py-1 text-right whitespace-nowrap">{row.quantity}</td>
              <td className="px-1.5 py-1">{row.unit}</td>
              <td className="px-1.5 py-1 text-right whitespace-nowrap">{formatCurrency(row.unitPrice)}</td>
              <td className="px-1.5 py-1 text-right whitespace-nowrap">{formatCurrency(row.totalAmount)}</td>
              <td className="px-1.5 py-1 text-right whitespace-nowrap">{formatCurrency(row.amountPaid)}</td>
              <td className="px-1.5 py-1 text-right whitespace-nowrap">{formatCurrency(row.balanceAmount)}</td>
              <td className="px-1.5 py-1" style={{ color: STATUS_INK[row.paymentStatus] }}>
                {PAYMENT_STATUS_LABEL[row.paymentStatus]}
              </td>
            </tr>
          ))}
        </tbody>
      </table>

      <footer className="mt-6 border-t border-slate-300 pt-2 text-[10px] text-slate-500">
        {organizationName} — Sales Product Tracking. Figures reflect only the rows visible under the
        filters above.
      </footer>
    </div>
  )
}

function Summary({ label, value }: { label: string; value: string }) {
  return (
    <div className="rounded border border-slate-300 px-2.5 py-2">
      <p className="text-[10px] uppercase tracking-wide text-slate-500">{label}</p>
      <p className="mt-0.5 text-sm font-semibold">{value}</p>
    </div>
  )
}